version: "3.9"

services:
  backend:
    image: user:1.0
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - app-network
  frontend:
    image: front:1.0
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - cart
      - order
      - payment
    networks:
      - app-network

  cart:
    image: cart:1.0
    container_name: cart-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  payment:
    image: payment:1.0
    container_name: payment-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  order:
    image: order:1.0
    container_name: order-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  product:
    image: product:1.0
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: mohan
      DB_PASSWORD: Amohan9676$
      DB_NAME: mydb
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Amohan9676$
      MYSQL_DATABASE: mydb
      MYSQL_USER: mohan
      MYSQL_PASSWORD: Amohan9676$
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  pgdata:
  mysql-data:

networks:
  app-network:
    driver: bridge



#   # db1:
#   #   image: postgres:15
#   #   container_name: frontend2-db1-1
#   #   restart: always
#   #   environment:
#   #     POSTGRES_USER: postgres
#   #     POSTGRES_PASSWORD: yourpassword
#   #     POSTGRES_DB: mydatabase
#   #   ports:
#   #     - "5433:5432"  # ✅ Changed host port to avoid conflict
#   #   volumes:
#   #     - postgres_data:/var/lib/postgresql/data
#   #   networks:
#   #     - app-network

#   # app:
#   #   image: go:1.0
#   #   container_name: frontend2-app-1
#   #   depends_on:
#   #     - db1
#   #   ports:
#   #     - "8080:8080"
#   #   environment:
#   #     DB_HOST: db1  # ✅ Connect to db1 by service name
#   #     DB_PORT: 5432
#   #     DB_USER: postgres
#   #     DB_PASSWORD: yourpassword
#   #     DB_NAME: mydatabase
#   #   networks:
#   #     - app-network

# volumes:
#   pgdata:
#   # postgres_data:

# networks:
#   app-network:
#     driver: bridge



# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: yourpassword
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   app:
#     image: go:1.0
#     depends_on:
#       - db
#     ports:
#       - "8080:8080"
#     environment:
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: yourpassword
#       DB_NAME: mydatabase

# volumes:
#   postgres_data:



