apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
    tier: frontend
    environment: dev
spec:
  replicas: 3  # Number of Pods to maintain
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      environment: dev
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        environment: dev
    spec:
      containers:
        - name: nginx-container
          image: frontend:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  labels:
    app: web
spec:
  selector:
    app: web
    tier: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 80   # Container port
# Optional: specify a port between 30000-32767
  type: NodePort
