name: CI Pipeline

on:
  push:
    branches:
      - dev
      - test
permissions:
  contents: read
  security-events: write


jobs:
  deploy_to_k8: 
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: just checking the code
        run: echo "please install it"
