on:
  push:
    branches:
      - '**'    # All branches
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'   # 👈 Only deploy if main branch!
    environment:
      name: production  # 👈 Triggers manual approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy step
        run: echo "Deploying main branch to Production..."
